# Generated by Django 5.2.4 on 2025-07-03 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='hall_images/')),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=8)),
                ('capacity', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('event_types', models.CharField(choices=[('birthday', 'Birthday'), ('marriage', 'Marriage'), ('party', 'Party'), ('private_movie', 'Private Movie'), ('other', 'Other')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
