# Generated by Django 5.2.4 on 2025-07-04 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0004_hallimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hall',
            name='image',
        ),
        migrations.AddField(
            model_name='hall',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='hall_images/', verbose_name='Cover Photo'),
        ),
    ]
